title: Splendeo Innovación
locales:
  es:
    name: Español
    path: ""
    navigation:
    - class: what-we-do
      text: Qué hacemos
      url: /que-hacemos/
    - class: who-we-are
      text: Quiénes somos
      url: /quienes-somos/
    - class: projects
      text: Proyectos
      url: /proyectos/
    - class: blog
      text: Blog
      url: /blog/
    footer:
      text: "Copyright &copy; Splendeo Innovación, SL 2010"
      legal_link:
      - "Aviso legal": "/aviso-legal/"
    contact:
      thank_you_url: /gracias/
      email:
        title: Tu dirección de correo
        help: Necesitamos tu dirección para poder responderte. No la utilizaremos para ningún otro fin.
        error: Por favor escribe una dirección de correo válida.
      header:
        title: Asunto del Mensaje
        help: Escribe aquí un título para tu mensaje.
        error: Por favor rellena el Asunto del Mensaje.
      body:
        title: Cuerpo del Mensaje
        help: Escribe tu comentario o pregunta aquí.
        error: Por favor rellena el Cuerpo del Mensaje.
      submit: Enviar
      link:
        text: Contacto
        url: /contacto/
        ajax: /contacto-ajax/

  en:
    name: English
    path: /en
    
    navigation:
    - class: what-we-do
      text: What we do
      url: /en/what-we-do/
    - class: who-we-are
      text: Who we are
      url: /en/who-we-are/
    - class: projects
      text: Projects
      url: /en/projects/
    - class: blog
      text: Blog
      url: /en/blog/
    footer:
      text: "Copyright &copy; Splendeo Innovación, SL 2010"
      legal_link:
      - "Legal notice": "/en/legal-notice/"
    contact:
      thank_you_url: /en/thank-you/
      email:
        title: Your email address
        help: We'll use it exclusively to answer to your email. We will not use it for any other purpose.
        error: Please enter a valid email address.
      header:
        title: Message Header
        help: Enter the title of your message here.
        error: Please provide a Message Header.
      body:
        title: Message Body
        help: Enter your complete comment or question here.
        error: Please fill in the Message Body.
      submit: Submit
      link:
        text: Contact
        url: /en/contact/
        ajax: /en/contact-ajax/

permalink: pretty
auto: true
server: true
lsi: false
pygments: true
