title: Splendeo Innovación
locales:
  es:
    name: Español
    path: ""
    navigation:
    - "Qué hacemos": /que-hacemos/
    - "Quiénes somos": /quienes-somos/
    - "Proyectos": /proyectos/
    - "Blog": /blog/
    footer:
      text: "Copyright &copy; Splendeo Innovación, SL 2010"
      legal_link:
      - "Aviso legal": "/aviso-legal/"
  en:
    name: English
    path: /en
    navigation:
    - "What we do": /en/what-we-do/
    - "Who we are": /en/who-we-are/
    - "Projects": /en/projects/
    - "Blog": /en/blog/
    footer:
      text: "Copyright &copy; Splendeo Innovación, SL 2010"
      legal_link:
      - "Legal notice": "/en/legal-notice/"

permalink: pretty
auto: true
server: true
lsi: false
pygments: true
