title: Splendeo Innovación
locales:
  es:
    name: Español
    path: /
    navigation:
    - "Qué hacemos": que-hacemos
    - "Quiénes somos": quienes-somos
    - "Proyectos": proyectos
    - "Blog": blog
  en:
    name: English
    path: /en/
    navigation:
    - "What we do": what-we-do
    - "Who we are": who-we-are
    - "Projects": projects
    - "Blog": blog

permalink: pretty
auto: true
server: true
lsi: false
pygments: true
