title: Splendeo Innovación
locales:
  es:
    name: Español
    path: ""
    navigation:
    - "Qué hacemos": /que-hacemos/
    - "Quiénes somos": /quienes-somos/
    - "Proyectos": /proyectos/index.html
    - "Blog": /blog/index.html
  en:
    name: English
    path: /en
    navigation:
    - "What we do": /en/what-we-do/
    - "Who we are": /en/who-we-are/
    - "Projects": /en/projects/index.html
    - "Blog": /en/blog/index.html

permalink: pretty
auto: true
server: true
lsi: false
pygments: true
