title: Splendeo Innovación
locales:
  es:
    name: Español
    path: ""
    navigation:
    - "Qué hacemos": /que-hacemos/
    - "Quiénes somos": /quienes-somos/
    - "Proyectos": /proyectos/
    - "Blog": /blog/
    footer:
      text: Copyright &copy; Splendeo Innovación 2010
      legal_link:
      - "Política de privacidad": /legal/
  en:
    name: English
    path: /en
    navigation:
    - "What we do": /en/what-we-do/
    - "Who we are": /en/who-we-are/
    - "Projects": /en/projects/
    - "Blog": /en/blog/
    footer:
      text: Copyright &copy; Splendeo Innovación 2010
      legal_link:
      - "Privacy policy": /en/legal/

permalink: pretty
auto: true
server: true
lsi: false
pygments: true
