title: Splendeo Innovación
url: http://www.splendeo.es
locales:
  es:
    name: Español
    path: ""
    navigation:
    - text: Qué hacemos
      url: /que-hacemos/
    - text: Quiénes somos
      url: /quienes-somos/
    - text: Proyectos
      url: /proyectos/
      ugly_url: /proyectos/index.html
      layout: project
    - text: Blog
      url: /blog/
      ugly_url: /blog/index.html
      layout: post
    footer:
      text: "Copyright &copy; Splendeo Innovación, SL 2010"
      legal_link:
      - "Aviso legal": "/aviso-legal/"
    contact:
      thank_you: Tu email ha sido enviado! Gracias!
      bad_email: Por favor incluye tu nombre, un email válido, el asunto, el mensaje y el resultado de la prueba anti-spam.
      name: Tu nombre
      email: Tu dirección de correo
      subject: Asunto de tu mensaje
      anti_spam: Para prevenir el SPAM - cuánto es 1 + 1?
      body: Mensaje
      submit: Enviar
      link:
        text: Contacto
        url: /contacto/
        image: /css/images/contact-es.gif

  en:
    name: English
    path: /en
    
    navigation:
    - text: What we do
      url: /en/what-we-do/
    - text: Who we are
      url: /en/who-we-are/
    - text: Projects
      url: /en/projects/
      ugly_url: /en/projects/index.html
      layout: project
    - text: Blog
      url: /en/blog/
      ugly_url: /en/blog/index.html
      layout: post
    footer:
      text: "Copyright &copy; Splendeo Innovación, SL 2010"
      legal_link:
      - "Legal notice": "/en/legal-notice/"
    contact:
      thank_you: Your email has been sent. Thank you!
      bad_email: Please include your name, valid email address, subject, message and the anti-spam test result.
      name: Your name
      email: Your email address
      subject: Message subject
      anti_spam: To prevent SPAM - how much is 1 + 1?
      body: Your message
      submit: Send
      link:
        text: Contact
        url: /en/contact/
        image: /css/images/contact-en.gif

permalink: pretty
auto: true
server: true
lsi: false
pygments: true

exclude: private


